### ISSUE TITLE
Base64.decode() is not working when I updated meteor version from meteor 1.4.2 to meteor 1.5

### ISSUE THREAD

**Issue by parveen-daffodil** [VeliovGroup/meteor-base64#1]

**Comment by dr-dimitru** [comment]
Hello @parveen-daffodil ,

 1. What exactly not working?
 2. Do you get any errors?
 3. Have you updated `ostrio:base64` package to the latest release?
 4. See [release notes](https://github.com/VeliovGroup/meteor-base64/releases) for major releases changes
 5. Quick guess is you're missing this:
```js
import { Base64 } from 'meteor/ostrio:base64';
```

**Comment by dr-dimitru** [comment]
I've run tests and found no issues on the latest Meteor.
To make sure I've published [`v1.2.3`](https://github.com/VeliovGroup/meteor-base64/releases/tag/1.2.3) with minor changes.

Please make sure you're on the latest release. ty.

**Comment by parveen-daffodil** [comment]
Hi @dr-dimitru 

- At first it was showing `[ReferenceError: Base64 is not defined]`.
- Then I add this statement in codebase `import { Base64 } from 'meteor/ostrio:base64';`
- Then Base64.decode() was not decoding the text properly, and throwing error unexpected token. 
After it decodes it shows content like this
![image](https://user-images.githubusercontent.com/5242589/31572942-b7541df0-b0ce-11e7-85f5-efb89f9a783a.png)

**Comment by dr-dimitru** [comment]
Could you please post your code sample and __short__ sample of encoded/plain string where this issue appears?

**Comment by parveen-daffodil** [comment]
Actually, I was getting content from github like this :

var result = github.repos.getContent({
                    user: user,
                    repo: repo,
                    path: path,
                    ref: ref
                });
For decoding result we were using this statement Base64.decode(result.content). But when I updated with 1.5 it was not working so I have fixed this issue by replacing above statement i.e Base64.decode(result.content) with

result = new Buffer(result.content, "base64").toString();
It has been resolved.

**Comment by dr-dimitru** [comment]
Well, great 🎉 
Btw this lib is meant to work with strings only, and it wasn't changed in any of the releases.
What was changes is Meteor's support of the Buffer polyfill, but I'm not sure how this is related.

I'm glad this is solved on your end.
Please support this project with:
 - A star on GitHub - https://github.com/VeliovGroup/meteor-base64
 - A star on Atmosphere - https://atmospherejs.com/ostrio/base64
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made

**Comment by parveen-daffodil** [comment]
@dr-dimitru , Are you saying that this statement `result = new Buffer(result.content, "base64").toString();` might stuck somewhere ?

**Comment by dr-dimitru** [comment]
Stuck? No.
Is this *Server* or *Client*?

**Comment by parveen-daffodil** [comment]
This is on server side actually. I meant when you say this `Btw this lib is meant to work with strings only` what do you mean by this ?

**Comment by dr-dimitru** [comment]
I mean you should pass string into its methods. So in your case if you have a *Buffer* you should convert it into the string, then pass into `encode`/`decode` methods.

That's why I've asked you for a code and data sample, but you have ignored that.
Could you at least `console.log(result)` for me?

Note: `new Buffer` is deprecated.

**Comment by parveen-daffodil** [comment]
![image](https://user-images.githubusercontent.com/5242589/31573873-b8642268-b0e1-11e7-9086-c59ee0d84381.png)
This is the screen shot for result on server side.

This is the screenshot of the code  which was causing problem :
![image](https://user-images.githubusercontent.com/5242589/31573908-0eb531ca-b0e2-11e7-8a1e-7a5320537e46.png)

**Comment by dr-dimitru** [comment]
Okay, thank you, now it's more clear.

 1. There is `\n` new line symbols in a `content` field.
 2. Could you try to sanitize is from those additives?
 3. If sanitization won't help - Could you try to use "Native" code as described [here](https://github.com/VeliovGroup/meteor-base64#native-code-support)?

**Comment by parveen-daffodil** [comment]
Sanitization is not possible.
Are yo saying to use these statements 
```
import { base64 } from 'meteor/ostrio:base64';
const nativeB64 = new base64(true, true);
```
and then 
`var base64 = nativeB64.decode(result.content);` right ?

**Comment by dr-dimitru** [comment]
> Sanitization is not possible.

Why? This won't work for you?
```js
var base64 = Base64.decode(result.content.replace(/\n|\r/gm, ''));
```

> Are you saying to use these statements

Yes, but sanitization, should help in first place

**Comment by dr-dimitru** [comment]
@parveen-daffodil have you tried with sanitized source?

**Comment by parveen-daffodil** [comment]
@dr-dimitru 
I did n't try sanitized code. Actually I was thinking that the content should contain `\n` because it was working before updating to meteor 1.5.

Now, I have tried this and I can see that it's working. Thanks. :)

**Comment by dr-dimitru** [comment]
Hi @parveen-daffodil ,

Thank you for update on this.

> Now, I have tried this and I can see that it's working

Didn't get, is it working with sanitization or native function?

> Actually I was thinking that the content should contain `\n` because it was working before updating to meteor 1.5.

Are you 100% sure file crawled from GitHub was containing `\n` before you updated?

**Comment by parveen-daffodil** [comment]
@dr-dimitru  
> Didn't get, is it working with sanitization or native function?

Now, I have done sanitization with code and can see it is working.

> Are you 100% sure file crawled from GitHub was containing \n before you updated?

Yes.

**Comment by dr-dimitru** [comment]
Well, I'm glad it work with sanitization now. No idea why it was working before, as it's not supposed to work with invalid base64 strings, as `\n` not a part if specs.

**Comment by parveen-daffodil** [comment]
@dr-dimitru Many Thanks for your help. :)
